# Generated by Django 5.2.1 on 2025-05-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_recreate_company_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ceo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
