# Generated by Django 5.2.1 on 2025-05-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_create_employee_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eployee',
        ),
    ]
