# Generated by Django 5.2.1 on 2025-05-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recreate_employee_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Manager', 'MGR'), ('Software Developer', 'SD'), ('Project Leader', 'PL')], max_length=50),
        ),
    ]
